version: '3.8'

services:
  # MongoDB - Primary Database (Game Configs, Events, Users)
  mongo:
    image: mongo:7.0
    container_name: projectpb-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  # Redis - Message Broker for WebSockets & Cache
  redis:
    image: redis:7.0-alpine
    container_name: projectpb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Mongo Express - Web UI for MongoDB (Optional, for Dev)
  mongo-express:
    image: mongo-express
    container_name: projectpb-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/
    depends_on:
      - mongo

  # Backend - Spring Boot API
  backend:
    build: ./backend
    container_name: projectpb-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  # Web - Next.js Frontend
  web:
    build: ./web
    container_name: projectpb-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data:
